"""identity columns on all primary keys

Revision ID: 4de0ce8d8f9a
Revises: 
Create Date: 2026-09-15 12:23:11.218068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de0ce8d8f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Todas las PK son "id" BIGINT NOT NULL sin IDENTITY ni DEFAULT (ver schema.sql). El backend no
# genera ids: los delega al motor agregando GENERATED BY DEFAULT AS IDENTITY (PLAN.md sección 3.2).
TABLAS = [
    "Especie_Pescado",
    "Pescador",
    "Pescado_individuo",
    "Relevamiento",
    "Reglamentacion",
    "Regla",
    "Fiscalizador",
    "Punto_desembarco",
]


def upgrade() -> None:
    for tabla in TABLAS:
        op.execute(f'ALTER TABLE "{tabla}" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY')


def downgrade() -> None:
    for tabla in TABLAS:
        op.execute(f'ALTER TABLE "{tabla}" ALTER COLUMN "id" DROP IDENTITY IF EXISTS')
